// Auto-generated by scripts/scraper.ts
// Last updated: 2025-12-01T15:09:07.141Z

export interface AITool {
  id: string;
  name: string;
  description: string;
  category: string;
  price: string;
  logo: string;
  website?: string;
  features?: string[];
  launchDate?: string;
  reviews: string;
  emoji?: string;
}

// Type guard to validate AITool objects
function isValidAITool(tool: any): tool is AITool {
  return (
    typeof tool.id === 'string' &&
    typeof tool.name === 'string' &&
    typeof tool.description === 'string' &&
    typeof tool.category === 'string' &&
    typeof tool.price === 'string' &&
    typeof tool.logo === 'string'
  );
}

// Search function that works with the current data structure
export function searchTools(query: string): AITool[] {
  const queryLower = query.toLowerCase();
  return aiTools.filter(tool => 
    tool.name.toLowerCase().includes(queryLower) ||
    tool.description.toLowerCase().includes(queryLower) ||
    tool.category.toLowerCase().includes(queryLower) ||
    (tool.website && tool.website.toLowerCase().includes(queryLower)) ||
    (tool.features && tool.features.some(feature => 
      feature.toLowerCase().includes(queryLower)
    ))
  );
}

export const aiTools: AITool[] = [
  {
    "id": "1",
    "name": "RoomX AI",
    "logo": "https://media.theresanaiforthat.com/icons/roomx-ai-virtual-staging-software.png?height=207",
    "description": "Transform vacant listings in 30 seconds with AI staging.",
    "category": "Virtual staging",
    "price": "Free + from $29/mo",
    "reviews": "38",
    "website": "https://theresanaiforthat.com/ai/roomx-ai-virtual-staging-software/"
  },
  {
    "id": "2",
    "name": "PXZ AI | Video Generator",
    "logo": "https://media.theresanaiforthat.com/icons/pxz-ai-video-generator.svg?height=207",
    "description": "Turn photos into videos with AI-powered camera movement.",
    "category": "Videos",
    "price": "Free + from $6.4/mo",
    "reviews": "54",
    "website": "https://theresanaiforthat.com/ai/pxz-ai-video-generator/"
  },
  {
    "id": "3",
    "name": "Revenuesurf",
    "logo": "https://media.theresanaiforthat.com/icons/revenuesurf.png?height=207",
    "description": "Generate blog posts that drive revenue.",
    "category": "SEO content",
    "price": "Free + from $99",
    "reviews": "93",
    "website": "https://theresanaiforthat.com/ai/revenuesurf/"
  },
  {
    "id": "4",
    "name": "PlatePhoto",
    "logo": "https://media.theresanaiforthat.com/icons/platephoto.svg?height=207",
    "description": "Generate professional AI food photos in seconds.",
    "category": "Food images",
    "price": "Free + from $10",
    "reviews": "44",
    "website": "https://theresanaiforthat.com/ai/platephoto/"
  },
  {
    "id": "5",
    "name": "DeepSeek",
    "logo": "https://media.theresanaiforthat.com/icons/deepseek.png?height=207",
    "description": "Unravel the mystery of AGI with curiosity",
    "category": "Productivity",
    "price": "#6 in Trending",
    "reviews": "17,905",
    "website": "https://theresanaiforthat.com/ai/deepseek/"
  },
  {
    "id": "6",
    "name": "AI Santa Claus",
    "logo": "https://media.theresanaiforthat.com/icons/ai-santa-claus.png?height=207",
    "description": "Bring Christmas magic to your kids with AI Santa.",
    "category": "Chatting with Santa",
    "price": "Free + from $9.99",
    "reviews": "1,704",
    "website": "https://theresanaiforthat.com/ai/ai-santa-claus/"
  },
  {
    "id": "7",
    "name": "AnyMusic",
    "logo": "https://media.theresanaiforthat.com/icons/anymusic.svg?height=207",
    "description": "Create AI music and lyrics free, no signup required.",
    "category": "Music",
    "price": "Free + from $19.9/mo",
    "reviews": "78",
    "website": "https://theresanaiforthat.com/ai/anymusic/"
  },
  {
    "id": "8",
    "name": "RapidMap",
    "logo": "https://media.theresanaiforthat.com/icons/rapidmap.png?height=207",
    "description": "Turn client workshops into professional deliverables in 30 minutes.",
    "category": "Process maps",
    "price": "Free + from $105/mo",
    "reviews": "148",
    "website": "https://theresanaiforthat.com/ai/rapidmap/"
  },
  {
    "id": "9",
    "name": "Discord DiscMeet",
    "logo": "https://media.theresanaiforthat.com/icons/discmeet.svg?height=207",
    "description": "Discord voice transcription and note taking app for teams and DnD sessions",
    "category": "Meeting notes",
    "price": "Free + from $9.99/mo",
    "reviews": "17,832",
    "website": "https://theresanaiforthat.com/ai/discmeet/"
  },
  {
    "id": "10",
    "name": "PDFClean.ai",
    "logo": "https://media.theresanaiforthat.com/icons/pdfclean-ai.svg?height=207",
    "description": "Convert PDF bank statements to clean Excel/CSV files.",
    "category": "PDF to Spreadsheets",
    "price": "Free + from $5",
    "reviews": "497",
    "website": "https://theresanaiforthat.com/ai/pdfclean-ai/"
  },
  {
    "id": "11",
    "name": "Vibe3D",
    "logo": "https://media.theresanaiforthat.com/icons/vibe3d.svg?height=207",
    "description": "Photorealistic AI renders in seconds",
    "category": "3D design",
    "price": "From $19/mo",
    "reviews": "128",
    "website": "https://theresanaiforthat.com/ai/vibe3d/"
  },
  {
    "id": "12",
    "name": "MuseVideo | Image to Image",
    "logo": "https://media.theresanaiforthat.com/icons/musevideo-image-to-image.svg?height=207",
    "description": "Transform and edit images with AI.",
    "category": "Image editing",
    "price": "Free + from $10.49/mo",
    "reviews": "371",
    "website": "https://theresanaiforthat.com/ai/musevideo-image-to-image/"
  },
  {
    "id": "13",
    "name": "OverseerOS",
    "logo": "https://media.theresanaiforthat.com/icons/overseeros.png?height=207",
    "description": "Clone any winning YouTube channel with AI.",
    "category": "Youtube strategies",
    "price": "Free + from $29/mo",
    "reviews": "178",
    "website": "https://theresanaiforthat.com/ai/overseeros/"
  },
  {
    "id": "14",
    "name": "Alai",
    "logo": "https://media.theresanaiforthat.com/icons/alai.svg?height=207",
    "description": "Create high quality presentations with AI",
    "category": "Presentations",
    "price": "Free + from $16/mo",
    "reviews": "10,915",
    "website": "https://theresanaiforthat.com/ai/alai/"
  },
  {
    "id": "15",
    "name": "Mimetic Labs",
    "logo": "https://media.theresanaiforthat.com/icons/mimetic-labs.svg?height=207",
    "description": "Transform ideas into printable 3D models with AI.",
    "category": "3D objects",
    "price": "Free + from $9.99",
    "reviews": "11,649",
    "website": "https://theresanaiforthat.com/ai/mimetic-labs/"
  },
  {
    "id": "16",
    "name": "Real Contracts",
    "logo": "https://media.theresanaiforthat.com/icons/realtorcontracts-ca.png?height=207",
    "description": "Top Realtors use AI to do all their paperwork",
    "category": "Real estate transactions",
    "price": "No pricing",
    "reviews": "992",
    "website": "https://theresanaiforthat.com/ai/realtorcontracts-ca/"
  },
  {
    "id": "17",
    "name": "Synpix",
    "logo": "https://media.theresanaiforthat.com/icons/synpix.svg?height=207",
    "description": "Dream it. Type it. Ship it.",
    "category": "Images",
    "price": "Free + from $13/mo",
    "reviews": "209",
    "website": "https://theresanaiforthat.com/ai/synpix/"
  },
  {
    "id": "18",
    "name": "ImageTranslator",
    "logo": "https://media.theresanaiforthat.com/icons/imagetranslator.svg?height=207",
    "description": "Translate text in photos instantly.",
    "category": "Image text translation",
    "price": "100% Free",
    "reviews": "193",
    "website": "https://theresanaiforthat.com/ai/imagetranslator/"
  },
  {
    "id": "19",
    "name": "AILightDesign",
    "logo": "https://media.theresanaiforthat.com/icons/ailightdesign.png?height=207",
    "description": "Visualize outdoor lighting designs on your actual photos.",
    "category": "Outdoor lighting",
    "price": "Free + from $10/mo",
    "reviews": "108",
    "website": "https://theresanaiforthat.com/ai/ailightdesign/"
  },
  {
    "id": "20",
    "name": "ArtPose",
    "logo": "https://media.theresanaiforthat.com/icons/artpose.svg?height=207",
    "description": "Generate stunning pose references instantly with AI.",
    "category": "Artistic poses",
    "price": "Free + from $9.9",
    "reviews": "122",
    "website": "https://theresanaiforthat.com/ai/artpose/"
  },
  {
    "id": "21",
    "name": "MarketAlerts.ai",
    "logo": "https://media.theresanaiforthat.com/icons/marketalerts.svg?height=207",
    "description": "Analyze stocks and find trade ideas with AI.",
    "category": "Stocks",
    "price": "Free + from $13.90/mo",
    "reviews": "32,604",
    "website": "https://theresanaiforthat.com/ai/marketalerts/"
  },
  {
    "id": "22",
    "name": "AI Coach That Sees/Talks/Pays (Impakt)",
    "logo": "https://media.theresanaiforthat.com/icons/impakt-ai-coach.png?height=207",
    "description": "Get Fit. Get Paid. AI Coach that sees, talks & pays.",
    "category": "Fitness",
    "price": "100% Free",
    "reviews": "43,240",
    "website": "https://theresanaiforthat.com/ai/impakt-ai-coach/"
  },
  {
    "id": "23",
    "name": "VidFlux AI | Text to Video",
    "logo": "https://media.theresanaiforthat.com/icons/vidflux-ai-text-to-video.svg?height=207",
    "description": "Transform any text into stunning videos instantly.",
    "category": "Videos",
    "price": "From $6.75/mo",
    "reviews": "695",
    "website": "https://theresanaiforthat.com/ai/vidflux-ai-text-to-video/"
  },
  {
    "id": "24",
    "name": "Sous | AI Recipe Generator & Kitchen Assistant",
    "logo": "https://media.theresanaiforthat.com/icons/sous-ai-recipe-generator.svg?height=207",
    "description": "All-in-one AI kitchen assistant: pantry management, recipe generation, meal planning, shopping lists",
    "category": "Recipes",
    "price": "Free + from $9.99/mo",
    "reviews": "867",
    "website": "https://theresanaiforthat.com/ai/sous-ai-recipe-generator/"
  },
  {
    "id": "25",
    "name": "CodeFlying",
    "logo": "https://media.theresanaiforthat.com/icons/codeflying.svg?height=207",
    "description": "Create full-stack apps by chatting with AI.",
    "category": "Vibe coding",
    "price": "Free + from $25/mo",
    "reviews": "657",
    "website": "https://theresanaiforthat.com/ai/codeflying/"
  },
  {
    "id": "26",
    "name": "DealNavigator.Ai",
    "logo": "https://media.theresanaiforthat.com/icons/dealnavigator.png?height=207",
    "description": "AI-powered deal intelligence for smarter negotiations.",
    "category": "Business intelligence",
    "price": "Free + from $299/mo",
    "reviews": "146",
    "website": "https://theresanaiforthat.com/ai/dealnavigator/"
  },
  {
    "id": "27",
    "name": "Aivvid AI",
    "logo": "https://media.theresanaiforthat.com/icons/aivvid-ai.svg?height=207",
    "description": "AI-powered video intelligence platform.",
    "category": "Videos",
    "price": "From $6.90/mo",
    "reviews": "354",
    "website": "https://theresanaiforthat.com/ai/aivvid-ai/"
  },
  {
    "id": "28",
    "name": "Rizzy - AI Lead Generator",
    "logo": "https://media.theresanaiforthat.com/icons/rizzy-ai-lead-generator.svg?height=207",
    "description": "Your 24/7 AI Lead Generator on X.",
    "category": "Lead generation",
    "price": "Free + from $49/mo",
    "reviews": "7,033",
    "website": "https://theresanaiforthat.com/ai/rizzy-ai-lead-generator/"
  },
  {
    "id": "29",
    "name": "Younet",
    "logo": "https://media.theresanaiforthat.com/icons/younet.png?height=207",
    "description": "Personalized AI agents that expedite your work 10X",
    "category": "Agents",
    "price": "Free + from $9.99/mo",
    "reviews": "88,086",
    "website": "https://theresanaiforthat.com/ai/younet/"
  },
  {
    "id": "30",
    "name": "VeriIA",
    "logo": "https://media.theresanaiforthat.com/icons/veriia.svg?height=207",
    "description": "AI detector for professional content.",
    "category": "AI content detection",
    "price": "Free + from $4.99",
    "reviews": "149",
    "website": "https://theresanaiforthat.com/ai/veriia/"
  },
  {
    "id": "31",
    "name": "Superway",
    "logo": "https://media.theresanaiforthat.com/icons/superway.svg?height=207",
    "description": "See Tomorrow's Trends Today.",
    "category": "Trend analysis",
    "price": "Free + from $35.00/mo",
    "reviews": "169",
    "website": "https://theresanaiforthat.com/ai/superway/"
  },
  {
    "id": "32",
    "name": "Infograph.app",
    "logo": "https://media.theresanaiforthat.com/icons/infograph-app.svg?height=207",
    "description": "From text to visualized infographics in one click.",
    "category": "Infographics",
    "price": "100% Free",
    "reviews": "236",
    "website": "https://theresanaiforthat.com/ai/infograph-app/"
  },
  {
    "id": "33",
    "name": "MSong.ai",
    "logo": "https://media.theresanaiforthat.com/icons/msong-ai.svg?height=207",
    "description": "Make songs with AI in seconds.",
    "category": "Music",
    "price": "Free + from $7.9/mo",
    "reviews": "388",
    "website": "https://theresanaiforthat.com/ai/msong-ai/"
  },
  {
    "id": "34",
    "name": "BeatViz AI Music Generator",
    "logo": "https://media.theresanaiforthat.com/icons/beatviz-ai-music-generator.svg?height=207",
    "description": "Skip the complexity. Create professional-quality music with simple prompts.",
    "category": "Music",
    "price": "Free + from $13.9/mo",
    "reviews": "209",
    "website": "https://theresanaiforthat.com/ai/beatviz-ai-music-generator/"
  },
  {
    "id": "35",
    "name": "AI UGC Creator",
    "logo": "https://media.theresanaiforthat.com/icons/ai-ugc-creator.png?height=207",
    "description": "Create professional UGC ads in 5 minutes without filming.",
    "category": "UGC videos",
    "price": "Free + from $14.25/mo",
    "reviews": "242",
    "website": "https://theresanaiforthat.com/ai/ai-ugc-creator/"
  },
  {
    "id": "36",
    "name": "NeuralTalk AI",
    "logo": "https://media.theresanaiforthat.com/icons/neuraltalk-ai.svg?height=207",
    "description": "Revolutionary AI chatbots for customer support.",
    "category": "Customer support",
    "price": "Free + from $29/mo",
    "reviews": "6,199",
    "website": "https://theresanaiforthat.com/ai/neuraltalk-ai/"
  },
  {
    "id": "37",
    "name": "SparkIcon AI",
    "logo": "https://media.theresanaiforthat.com/icons/sparkicon-ai.svg?height=207",
    "description": "Instantly generate high-quality icons with AI creativity.",
    "category": "Icons",
    "price": "Free + from $5",
    "reviews": "4,600",
    "website": "https://theresanaiforthat.com/ai/sparkicon-ai/"
  },
  {
    "id": "38",
    "name": "CoSupport AI",
    "logo": "https://media.theresanaiforthat.com/icons/cosupport-ai.svg?height=207",
    "description": "AI support agents that don’t hallucinate, live in minutes",
    "category": "Customer support",
    "price": "Free + from $-2",
    "reviews": "13,629",
    "website": "https://theresanaiforthat.com/ai/cosupport-ai/"
  },
  {
    "id": "39",
    "name": "Rank++",
    "logo": "https://media.theresanaiforthat.com/icons/rankplusplus.svg?height=207",
    "description": "Boost your visibility in AI answers with Rank++",
    "category": "Answer engine optimization",
    "price": "Free + from $49/mo",
    "reviews": "1,897",
    "website": "https://theresanaiforthat.com/ai/rankplusplus/"
  },
  {
    "id": "40",
    "name": "FocuSee",
    "logo": "https://media.theresanaiforthat.com/icons/focusee.svg?height=207",
    "description": "Auto-polish screen recordings with smart zoom effects.",
    "category": "Screen recordings",
    "price": "Free + from $19.99/mo",
    "reviews": "12,445",
    "website": "https://theresanaiforthat.com/ai/focusee/"
  },
  {
    "id": "41",
    "name": "PoYo.ai",
    "logo": "https://media.theresanaiforthat.com/icons/poyo-ai.svg?height=207",
    "description": "Premium AI models through one unified API.",
    "category": "APIs",
    "price": "No pricing",
    "reviews": "232",
    "website": "https://theresanaiforthat.com/ai/poyo-ai/"
  },
  {
    "id": "42",
    "name": "GMapsScraper AI",
    "logo": "https://media.theresanaiforthat.com/icons/gmapsscraper-ai.svg?height=207",
    "description": "Extract 1,000+ verified leads from Google Maps instantly.",
    "category": "Data extraction",
    "price": "Free + from $39/mo",
    "reviews": "206",
    "website": "https://theresanaiforthat.com/ai/gmapsscraper-ai/"
  },
  {
    "id": "43",
    "name": "LetsMkVideo",
    "logo": "https://media.theresanaiforthat.com/icons/letsmkvideo.svg?height=207",
    "description": "Create stunning videos from text and images.",
    "category": "Videos",
    "price": "Free + from $15.9/mo",
    "reviews": "775",
    "website": "https://theresanaiforthat.com/ai/letsmkvideo/"
  },
  {
    "id": "44",
    "name": "AI Image Editor.info",
    "logo": "https://media.theresanaiforthat.com/icons/ai-image-editor-info.svg?height=207",
    "description": "Upload photos and let AI transform them instantly.",
    "category": "Image editing",
    "price": "Free + from $19.99/mo",
    "reviews": "600",
    "website": "https://theresanaiforthat.com/ai/ai-image-editor-info/"
  },
  {
    "id": "45",
    "name": "Editee - AI Photo Editor",
    "logo": "https://media.theresanaiforthat.com/icons/editee-ai-photo-editor.png?height=207",
    "description": "Transform photos with next-gen AI editing tools.",
    "category": "Image editing",
    "price": "Free + from $10/mo",
    "reviews": "347",
    "website": "https://theresanaiforthat.com/ai/editee-ai-photo-editor/"
  },
  {
    "id": "46",
    "name": "Touchpoint",
    "logo": "https://media.theresanaiforthat.com/icons/touchpoint.svg?height=207",
    "description": "Create designer-quality email templates with AI",
    "category": "Email templates",
    "price": "Free + from $20/mo",
    "reviews": "3,516",
    "website": "https://theresanaiforthat.com/ai/touchpoint/"
  },
  {
    "id": "47",
    "name": "Talk To Myra",
    "logo": "https://media.theresanaiforthat.com/icons/talk-to-myra.svg?height=207",
    "description": "Turn memories into timeless keepsakes.",
    "category": "Keepsakes",
    "price": "From $9.95/mo",
    "reviews": "2,596",
    "website": "https://theresanaiforthat.com/ai/talk-to-myra/"
  },
  {
    "id": "48",
    "name": "DET Practice",
    "logo": "https://media.theresanaiforthat.com/icons/det-practice.svg?height=207",
    "description": "Ace the Duolingo English Test with AI-powered practice.",
    "category": "DET preparation",
    "price": "Free + from $7.9/mo",
    "reviews": "2,711",
    "website": "https://theresanaiforthat.com/ai/det-practice/"
  },
  {
    "id": "49",
    "name": "Offtrack - AI DJ App",
    "logo": "https://media.theresanaiforthat.com/icons/offtrack-ai-dj-app.svg?height=207",
    "description": "Your AI DJ shortens songs with seamless transitions.",
    "category": "Dj mixing assistance",
    "price": "Free + from $4.99/mo",
    "reviews": "148",
    "website": "https://theresanaiforthat.com/ai/offtrack-ai-dj-app/"
  },
  {
    "id": "50",
    "name": "Affint",
    "logo": "https://media.theresanaiforthat.com/icons/affint.svg?height=207",
    "description": "The First AI-Native Workspace",
    "category": "Productivity",
    "price": "Free + from $20/mo",
    "reviews": "7,245",
    "website": "https://theresanaiforthat.com/ai/affint/"
  },
  {
    "id": "51",
    "name": "MusicArt AI",
    "logo": "https://media.theresanaiforthat.com/icons/musicart-ai.svg?height=207",
    "description": "Express Your Art with AI Music Maker",
    "category": "Music",
    "price": "Free + from $10.49/mo",
    "reviews": "141",
    "website": "https://theresanaiforthat.com/ai/musicart-ai/"
  },
  {
    "id": "52",
    "name": "Vertech Academy",
    "logo": "https://media.theresanaiforthat.com/icons/vertech-academy.svg?height=207",
    "description": "AI That Actually Teaches You",
    "category": "Studying",
    "price": "Free + from $4.99",
    "reviews": "88,180",
    "website": "https://theresanaiforthat.com/ai/vertech-academy/"
  },
  {
    "id": "53",
    "name": "MusicAI.ai",
    "logo": "https://media.theresanaiforthat.com/icons/musicai-ai.svg?height=207",
    "description": "Turn ideas and lyrics into royalty-free music in seconds.",
    "category": "Music",
    "price": "Free + from $10.49/mo",
    "reviews": "224",
    "website": "https://theresanaiforthat.com/ai/musicai-ai/"
  },
  {
    "id": "54",
    "name": "UXMagic AI",
    "logo": "https://media.theresanaiforthat.com/icons/uxmagic-ai.svg?height=207",
    "description": "Generate Figma-ready UI designs with AI instantly.",
    "category": "UX design",
    "price": "Free + from $17.5/mo",
    "reviews": "5,188",
    "website": "https://theresanaiforthat.com/ai/uxmagic-ai/"
  },
  {
    "id": "55",
    "name": "Pixwith AI",
    "logo": "https://media.theresanaiforthat.com/icons/pixwith-ai.svg?height=207",
    "description": "Create stunning AI videos & images in minutes.",
    "category": "Videos",
    "price": "Free + from $9.99",
    "reviews": "729",
    "website": "https://theresanaiforthat.com/ai/pixwith-ai/"
  },
  {
    "id": "56",
    "name": "TGDesk",
    "logo": "https://media.theresanaiforthat.com/icons/tgdesk.svg?height=207",
    "description": "Turn Telegram groups into automated lead generators.",
    "category": "Customer engagement",
    "price": "Free + from $49.99/mo",
    "reviews": "212",
    "website": "https://theresanaiforthat.com/ai/tgdesk/"
  },
  {
    "id": "57",
    "name": "MakeShot AI",
    "logo": "https://media.theresanaiforthat.com/icons/makeshot.svg?height=207",
    "description": "Easy AI video and image creator for pros.",
    "category": "Videos",
    "price": "From $25/mo",
    "reviews": "10,496",
    "website": "https://theresanaiforthat.com/ai/makeshot/"
  },
  {
    "id": "58",
    "name": "Snaploid",
    "logo": "https://media.theresanaiforthat.com/icons/snaploid.svg?height=207",
    "description": "Turn photos into classic Polaroids with AI.",
    "category": "Image editing",
    "price": "Free + from $11.9/mo",
    "reviews": "339",
    "website": "https://theresanaiforthat.com/ai/snaploid/"
  },
  {
    "id": "59",
    "name": "Hairstyle Changer by LEMONO AI",
    "logo": "https://media.theresanaiforthat.com/icons/hairstyle-changer-by-lemono-ai.svg?height=207",
    "description": "Try new hairstyles in seconds",
    "category": "Hairstyles",
    "price": "Free + from $9.99/mo",
    "reviews": "233",
    "website": "https://theresanaiforthat.com/ai/hairstyle-changer-by-lemono-ai/"
  },
  {
    "id": "60",
    "name": "LumeFlow AI",
    "logo": "https://media.theresanaiforthat.com/icons/lumeflow-ai.svg?height=207",
    "description": "Create AI videos in clicks.",
    "category": "Videos",
    "price": "From $6.99/mo",
    "reviews": "374",
    "website": "https://theresanaiforthat.com/ai/lumeflow-ai/"
  },
  {
    "id": "61",
    "name": "Taplio",
    "logo": "https://media.theresanaiforthat.com/icons/taplio.svg?height=207",
    "description": "The LinkedIn growth tool to turn content into pipeline",
    "category": "LinkedIn",
    "price": "Free + from $39/mo",
    "reviews": "30,272",
    "website": "https://theresanaiforthat.com/ai/taplio/"
  },
  {
    "id": "62",
    "name": "Notis",
    "logo": "https://media.theresanaiforthat.com/icons/notis-ai.svg?height=207",
    "description": "Your AI Intern One Message Away From All Your Tool Stack.",
    "category": "Personal assistant",
    "price": "Free + from $20/mo",
    "reviews": "454,349",
    "website": "https://theresanaiforthat.com/ai/notis-ai/"
  },
  {
    "id": "63",
    "name": "AI Clothes Changer",
    "logo": "https://media.theresanaiforthat.com/icons/ai-clothes-changer-1764233070.svg?height=207",
    "description": "Experience the fastest, most accurate virtual try-on.",
    "category": "Virtual try-ons",
    "price": "From $4.99",
    "reviews": "199",
    "website": "https://theresanaiforthat.com/ai/ai-clothes-changer-1764233070/"
  },
  {
    "id": "64",
    "name": "Belin Doc",
    "logo": "https://media.theresanaiforthat.com/icons/belin-doc.svg?height=207",
    "description": "One-click high-quality AI document translation.",
    "category": "Document translation",
    "price": "Free + from $16/mo",
    "reviews": "211",
    "website": "https://theresanaiforthat.com/ai/belin-doc/"
  },
  {
    "id": "65",
    "name": "Invent | AI Assistants",
    "logo": "https://media.theresanaiforthat.com/icons/invent-ai-assistants.svg?height=207",
    "description": "Create AI assistants that chat, talk, and answer from your data.",
    "category": "Customer support",
    "price": "Free + from $0.0009",
    "reviews": "24,351",
    "website": "https://theresanaiforthat.com/ai/invent-ai-assistants/"
  },
  {
    "id": "66",
    "name": "TrackMyBusiness",
    "logo": "https://media.theresanaiforthat.com/icons/trackmybusiness.svg?height=207",
    "description": "Your Search Console for AI chatbots.",
    "category": "Brand monitoring",
    "price": "Free + from $19/mo",
    "reviews": "96",
    "website": "https://theresanaiforthat.com/ai/trackmybusiness/"
  },
  {
    "id": "67",
    "name": "WayinVideo",
    "logo": "https://media.theresanaiforthat.com/icons/wayinvideo.svg?height=207",
    "description": "Turn video moments into viral clips instantly.",
    "category": "Video editing",
    "price": "Free + from $4.99/mo",
    "reviews": "228",
    "website": "https://theresanaiforthat.com/ai/wayinvideo/"
  },
  {
    "id": "68",
    "name": "GoatRemote",
    "logo": "https://media.theresanaiforthat.com/icons/goatremote.svg?height=207",
    "description": "Turn your Apple TV remote into a smart Mac controller.",
    "category": "Voice commands",
    "price": "From $15",
    "reviews": "359",
    "website": "https://theresanaiforthat.com/ai/goatremote/"
  },
  {
    "id": "69",
    "name": "AI Outfit Generator | AILabTools",
    "logo": "https://media.theresanaiforthat.com/icons/ai-outfit-generator-ailabtools.svg?height=207",
    "description": "Virtual try-on clothes with AI instantly.",
    "category": "Virtual try-ons",
    "price": "Free + from $4.99/mo",
    "reviews": "305",
    "website": "https://theresanaiforthat.com/ai/ai-outfit-generator-ailabtools/"
  },
  {
    "id": "70",
    "name": "Soundwise.ai",
    "logo": "https://media.theresanaiforthat.com/icons/soundwise-ai.svg?height=207",
    "description": "Free forever AI audio video transcription tool.",
    "category": "Transcription",
    "price": "Free + from $10/mo",
    "reviews": "283",
    "website": "https://theresanaiforthat.com/ai/soundwise-ai/"
  },
  {
    "id": "71",
    "name": "Ivory-App",
    "logo": "https://media.theresanaiforthat.com/icons/ivory-app.svg?height=207",
    "description": "Convert piano audio to sheet music using AI.",
    "category": "Music transcription",
    "price": "Free + from $9.99/mo",
    "reviews": "107",
    "website": "https://theresanaiforthat.com/ai/ivory-app/"
  },
  {
    "id": "72",
    "name": "Parser by Bix-Tech",
    "logo": "https://media.theresanaiforthat.com/icons/parser-by-bix-tech.svg?height=207",
    "description": "Extract data from any document automatically with AI.",
    "category": "Document data extraction",
    "price": "Free + from $0.06",
    "reviews": "3,117",
    "website": "https://theresanaiforthat.com/ai/parser-by-bix-tech/"
  },
  {
    "id": "73",
    "name": "Konvart",
    "logo": "https://media.theresanaiforthat.com/icons/konvart.svg?height=207",
    "description": "All-in-one SEO tool for research, optimisation, and ranking improvement.",
    "category": "SEO",
    "price": "Free + from $69/mo",
    "reviews": "5,816",
    "website": "https://theresanaiforthat.com/ai/konvart/"
  },
  {
    "id": "74",
    "name": "Estimatic AI - Winning Estimates For Contractors",
    "logo": "https://media.theresanaiforthat.com/icons/estimatic-ai.svg?height=207",
    "description": "Create accurate estimates in minutes with AI.",
    "category": "Construction cost estimation",
    "price": "Free + from $29/mo",
    "reviews": "5,743",
    "website": "https://theresanaiforthat.com/ai/estimatic-ai/"
  },
  {
    "id": "75",
    "name": "Feen AI - Homework Helper",
    "logo": "https://media.theresanaiforthat.com/icons/feen-ai-homework-helper.svg?height=207",
    "description": "AI homework helper for all subjects.",
    "category": "Homework",
    "price": "Free + from $6/mo",
    "reviews": "184",
    "website": "https://theresanaiforthat.com/ai/feen-ai-homework-helper/"
  },
  {
    "id": "76",
    "name": "LinkerFlow",
    "logo": "https://media.theresanaiforthat.com/icons/linkerflow.svg?height=207",
    "description": "Your SEO internal linking automated for Webflow",
    "category": "Internal links",
    "price": "Free + from $29/mo",
    "reviews": "3,931",
    "website": "https://theresanaiforthat.com/ai/linkerflow/"
  },
  {
    "id": "77",
    "name": "Lovely Rita's Jewelry Advisor",
    "logo": "https://media.theresanaiforthat.com/icons/lovely-rita-s-jewelry-advisor.svg?height=207",
    "description": "AI chatbot for everyday problem-solving and learning.",
    "category": "Jewelry recommendations",
    "price": "100% Free",
    "reviews": "230",
    "website": "https://theresanaiforthat.com/ai/lovely-rita-s-jewelry-advisor/"
  },
  {
    "id": "78",
    "name": "Image Animator AI",
    "logo": "https://media.theresanaiforthat.com/icons/image-animator-ai.svg?height=207",
    "description": "Animate still images into dynamic videos with AI.",
    "category": "Image to video",
    "price": "Free + from $1.5",
    "reviews": "1,162",
    "website": "https://theresanaiforthat.com/ai/image-animator-ai/"
  },
  {
    "id": "79",
    "name": "TradeWind AI",
    "logo": "https://media.theresanaiforthat.com/icons/tradewind-ai.svg?height=207",
    "description": "AI finds global buyers and closes deals automatically.",
    "category": "Lead generation",
    "price": "Free + from $49/mo",
    "reviews": "5,925",
    "website": "https://theresanaiforthat.com/ai/tradewind-ai/"
  },
  {
    "id": "80",
    "name": "remio: Your Personal ChatGPT",
    "logo": "https://media.theresanaiforthat.com/icons/remio.svg?height=207",
    "description": "Get Tailored Answer with Your Personal ChatGPT",
    "category": "Knowledge bases",
    "price": "Free + from $8.25/mo",
    "reviews": "364,297",
    "website": "https://theresanaiforthat.com/ai/remio/"
  }
];

// Export unique categories derived from the tools data
export const categories: string[] = Array.from(
  new Set(aiTools.map(tool => tool.category))
).sort((a, b) => a.localeCompare(b));